---
title: "Pteropod exposure analysis"
author: ""
output: 
  html_document:
    code_folding: hide
    css: kable.css
self_contained: yes
runtime: shiny
---

```{r, message = F, warning = F}
library(knitr)
opts_chunk$set(warning = FALSE, message = FALSE, dev.args = list(bg = 'transparent'), eval = T)

library(tidyverse)
library(vegan)
library(ggord)
library(scales)
library(effects)
library(shiny)
library(plotly)

source("R/funcs.R")

data(envdat)
data(expdat)

envchr <- c('pCO2', 'pH', 'TA', 'Ara', 'O2', 'Temp', 'Fluor')
```

A simple plot:
```{r, fig.height = 4, fig.width = 7}
toplo <- expdat %>% 
  unite('temp, pCO2', temp_trt, pco2_trt, sep = '/') %>% 
  mutate(
    `temp, pCO2` = factor(`temp, pCO2`, levels = c('lo/lo', 'lo/hi', 'hi/lo' ,'hi/hi'))
  )

ggplot(toplo, aes(x = `temp, pCO2`, y = alive)) +
  scale_y_continuous('% alive') +
  geom_boxplot(outlier.size = -1) +
  geom_jitter(alpha = 0.3, width = 0.15) + 
  theme_bw(base_family = 'serif')
```

Another simple plot:
```{r, fig.height = 4, fig.width = 7}
toplo <- expdat %>% 
  group_by(temp_trt, pco2_trt) %>% 
  summarize(
    ave = mean(alive, na.rm = T),
    lov = t.test(alive)$conf.int[1],
    hiv = t.test(alive)$conf.int[2]
  ) %>% 
  ungroup %>% 
  mutate(
    temp_trt = factor(temp_trt, levels = c('lo', 'hi')),
    pco2_trt = factor(pco2_trt, levels = c('lo', 'hi'))
  )

allv <- expdat %>% 
  mutate(
    temp_trt = factor(temp_trt, levels = c('lo', 'hi')),
    pco2_trt = factor(pco2_trt, levels = c('lo', 'hi'))
  ) %>%
  select(alive, temp_trt, pco2_trt, CTD) %>% 
  group_by(temp_trt, pco2_trt, CTD) %>%
  mutate(
    rep = 1, 
    rep = cumsum(rep)
    ) %>% 
  unite('uni', CTD, temp_trt, rep, remove = F)

ggplot(toplo, aes(x = pco2_trt, colour = temp_trt)) + 
  geom_line(data = allv, aes(y = alive, group = uni), linetype = 'dotted') +
  geom_point(size = 5, aes(y = ave)) + 
  geom_errorbar(aes(ymin = lov, ymax = hiv), width = 0.1, size = 1.5) +
  geom_line(aes(y = ave, group = temp_trt), size = 1.5) +
  scale_y_continuous('% alive') + 
  theme_bw(base_family = 'serif')
```

Run a simple test:
```{r}
mod <- lm(asin(alive / 100) ~ temp_trt * pco2_trt, data = expdat)
summary(mod)
```

No interaction:
```{r}
mod <- lm(asin(alive / 100) ~ temp_trt + pco2_trt, data = expdat)
summary(mod)
```

Compare with environmental parameters:
```{r}

tomod <- expdat %>% 
  left_join(envdat, by = 'CTD') %>% 
  unite(`temp, pCO2`, temp_trt, pco2_trt, sep = '/') %>% 
  mutate(
    `temp, pCO2` = factor(`temp, pCO2`, levels = c('lo/lo', 'lo/hi', 'hi/lo' ,'hi/hi')),
    alive_tr = asin(alive / 100)
  )

selectInput("vr", "Choose a variable to plot again survivorship:", envchr)
selectInput("trt", "Choose a treatment (temp, pCO2):", as.character(levels(tomod$`temp, pCO2`)))

plovrid <- reactive({

  # assign variable selection to name
  names(tomod)[names(tomod) %in% input$vr] <- 'xval'
  
  # filter by treatment
  filt_tomod <- tomod %>% 
    filter(`temp, pCO2` %in% input$trt)
  
  p <- ggplot(filt_tomod, aes(x = xval, y = alive)) + 
    geom_point(size = 5) + 
    scale_y_continuous('% alive') + 
    coord_cartesian(ylim = c(0, 105)) +
    theme_bw(base_family = 'serif') + 
    scale_x_continuous(input$vr) + 
    stat_smooth(method = 'lm') +
    ggtitle('identity')

  return(p)
  
})

plovr <- reactive({

  # assign variable selection to name
  names(tomod)[names(tomod) %in% input$vr] <- 'xval'
  
  # filter by treatment
  filt_tomod <- tomod %>% 
    filter(`temp, pCO2` %in% input$trt)
  
  p <- ggplot(filt_tomod, aes(x = xval, y = alive_tr)) + 
    geom_point(size = 5) + 
    scale_y_continuous('% alive (arcsine)') + 
    coord_cartesian(ylim = c(0, 1.4)) +
    theme_bw(base_family = 'serif') + 
    scale_x_continuous(input$vr) + 
    stat_smooth(method = 'lm') +
    ggtitle('transformed')

  return(p)
  
})

renderPlot({plovrid()}, height = 300, width = 600)
renderPlot({plovr()}, height = 300, width = 600)
```

```{r, eval = T}
# all correlations
crs <- tomod %>% 
  select(-CTD) %>% 
  filter(!`temp, pCO2` %in% 'hi/hi') %>% 
  gather('var', 'val', -`temp, pCO2`, -alive_tr, -alive) %>% 
  gather('alvvr', 'alvvl', alive_tr, alive) %>% 
  group_by(`temp, pCO2`, alvvr, var) %>% 
  nest %>% 
  mutate(
    
    crs = map(data, function(x){
      
      # variables
      vr1 <- x$alvvl
      vr2 <- x$val

      # pearson
      pr_ts <- cor.test(vr1, vr2, method = 'pearson')
      pr_cr <- round(pr_ts$estimate, 2)
      pr_pv <- p_ast(pr_ts$p.value)
      pr <- paste(pr_cr, pr_pv)
      
      # spearman
      sp_ts <- suppressWarnings(cor.test(vr1, vr2, method = 'spearman'))
      sp_cr <- round(sp_ts$estimate, 2)
      sp_pv <- p_ast(sp_ts$p.value)
      sp <- paste(sp_cr, sp_pv)

      out <- data.frame(pr = pr, sp = sp, stringsAsFactors = F)
      return(out)
      
    })
  ) %>% 
  select(-data) %>% 
  unnest %>% 
  gather('cortyp', 'corval', pr, sp) %>% 
  spread(var, corval) %>% 
  rename(response = alvvr) %>% 
  mutate(response = factor(response, levels = c('alive', 'alive_tr'), labels = c('identity', 'arcsine'))) %>% 
  arrange(cortyp, response, `temp, pCO2`)
```

```{r, eval = T}
knitr::kable(crs, caption = 'Pearson and Spearman correlations of survival (identity and arcsine) by variable')
```

# Pairwise linear models by treatment

```{r}

env_cmb <- envchr  %>% 
  combn(2) %>% 
  t %>% 
  data.frame(stringsAsFactors = F) %>%
  crossing(trt = levels(tomod$`temp, pCO2`), res = c('alive', 'alive_tr'), .) %>% 
  filter(!trt %in% c("hi/hi")) 

# all correlations
mod_all <- env_cmb %>% 
  t %>% 
  data.frame(stringsAsFactors = F) %>% 
  as.list %>% 
  map(function(x){
  
    # formula
    frm <- paste(x[[2]], '~', x[[3]], '*', x[[4]]) %>% 
      as.formula

    # model only
    trt <<- which(tomod$`temp, pCO2` %in% x[[1]])
    mod <- lm(frm, tomod, subset = trt)
    
    levs1 <- quantile(mod$model[, 2],  c(0, 1)) %>% 
      list
    names(levs1) <- names(mod$model)[2]
    

    levs2 <- quantile(mod$model[, 3], c(0, 1)) %>% 
      list
    names(levs2) <- names(mod$model)[3]

    trm <- mod %>% coefficients %>% names %>% .[4]    
    eff1 <- plot(effect(trm, mod, xlevels = levs1), multiline = T)
    eff2 <- plot(effect(trm, mod, xlevels = levs2), multiline = T)
   
    out <- list(mod = mod, eff1 = eff1, eff2 = eff2)

    return(out)
      
  }) %>% 
  enframe('Model', 'Modobj') %>% 
  mutate(Model = gsub('^X', 'mod', Model)) %>% 
  bind_cols(env_cmb) %>% 
  mutate(
    Modsum = map(Modobj, function(x){

      x <- x$mod
      
      # rsq
      rsq <- summary(x) %>% 
        .$r.squared
      
      # coeff summary
      out <- x %>% 
        summary %>% 
        .$coefficients %>% 
        .[-1, c(1, 4)] %>% 
        data.frame %>% 
        rownames_to_column('Env') %>% 
        mutate(
          Res = formula(x)[2] %>% as.character,
          Rsq = round(rsq, 2),
          Est = round(Estimate, 2), 
          Pvl = p_ast(Pr...t..)
        ) %>% 
        select(Res, Env, Rsq, Est, Pvl)
    
    return(out)
      
    })
  ) 

mods <- mod_all %>%
  select(-Modobj) %>%
  unnest %>% 
  select(-res, -X1, -X2)

```


```{r}
sellab <- env_cmb %>% 
  bind_cols(md = paste0('mod', seq(1:nrow(mod_all))), .) %>% 
  unite('vr', trt, res, X1, X2, sep = ', ') %>% 
  unite('vr2', md, vr, sep = ': ') %>% 
  unlist %>% 
  as.character

selectInput("mod", "Choose model:", sellab)

md <- reactive({

  tosel <- strsplit(input$mod, ':')[[1]][1]
  
  md <- filter(mod_all, Model %in% tosel) %>% 
  .$Modobj %>% 
  .[[1]]
  
  return(md)
  
})


renderPrint({summary(md()$mod)})

renderPlot({
  toplo <- md()$mod %>% 
    .$model %>% 
    gather('var', 'val', -1)

  ggplot(toplo, aes_string(x='val', y=names(toplo)[1])) +
    geom_point() + 
    facet_wrap(~var, ncol = 2, scales = 'free_x') + 
    theme_bw(base_family = 'serif') + 
    geom_smooth(method = 'lm') + 
    theme(axis.title.x = element_blank())

}, height = 300, width = 600)

prd_vl <- reactive({
  
  md <- md()$mod
  x <- md$model %>% 
    .[, -1] %>% 
    data.frame %>% 
    as.list %>% 
    map(range) %>%
    map(function(x) seq(x[1], x[2], length = 100))
  
  nms <- names(x) 
  x <- crossing(x[[1]], x[[2]])
  names(x) <- nms
  
  prd_vl <- predict(md, newdata = x) %>% 
    data.frame(., x)
  names(prd_vl)[1] <- all.vars(formula(md))[1]

  return(prd_vl)
  
})

renderPlot({
  md()$eff1
}, height = 300, width = 600)

renderPlot({
  md()$eff2
}, height = 300, width = 600)

renderPlot({
  
  pbase <- theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1, size = 10), 
    axis.text.y = element_text(size = 10),
    legend.position = 'top', 
    plot.margin = grid::unit(c(2, 2, 2, 2), 'pt'), 
    strip.background = element_blank(), 
    strip.text.y = element_text(angle = 0, hjust = 0, vjust = 0.5)
  ) 

  p <- ggplot(prd_vl(), aes_string(y = names(prd_vl())[2], x = names(prd_vl())[3], fill = names(prd_vl())[1])) + 
    geom_tile(colour = 'black') + 
    theme_bw(base_family = 'serif') +
    pbase +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) +
    scale_fill_distiller(palette = 'Spectral') +
    guides(fill = guide_colourbar(barheight = 0.5, barwidth = 15, label.theme = element_text(size = 12, angle = 0)))
  p
}, height = 700, width = 700)

renderPlotly({
  
  dat <- prd_vl() %>% 
    spread_(key_col = names(.)[2], value_col = names(.)[1]) %>% 
    .[,-1] %>% 
    as.matrix
    
  scene <- list(
    aspectmode = 'manual', 
    aspectratio = list(x = 1, y = 1, z = 0.5), 
    xaxis = list(title = names(prd_vl()[3])),
    yaxis = list(title = names(prd_vl()[2])),
    zaxis = list(title = names(prd_vl()[1]))
    )
  
  p <- plot_ly(z = ~dat) %>% add_surface(colors = rev(RColorBrewer::brewer.pal(11, 'Spectral'))) %>% 
    layout(scene = scene)
  p

})
```

# {.tabset}

## Temp hi, pCO2 lo

Identity response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'hi/lo' & mods$Res %in% 'alive'))
```

Arcsine response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'hi/lo' & mods$Res %in% 'alive_tr'))
```

## Temp lo, pCO2 hi

Identity response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'lo/hi' & mods$Res %in% 'alive'))
```

Arcsine response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'lo/hi' & mods$Res %in% 'alive_tr'))
```

## Temp lo, pCO2 lo

Identity response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'lo/lo' & mods$Res %in% 'alive'))
```

Arcsine response:

```{r}
knitr::kable(filter(mods, mods$trt %in% 'lo/lo' & mods$Res %in% 'alive_tr'))
```


