---
title: "Reviewer 2 response"
output: 
  bookdown::word_document2:
    reference_docx: my_styles.docx
urlcolor: blue
link-citations: true
---

__The information that the authors added about the methods is useful for better understanding the design of the study. I still have unresolved questions about the statistical analysis and therefore the results. It is still not clear how the statistical analyses were performed with respect to colinear drivers. For example, in Figure 4, you show that pCO2, pH, and O2 all covary - so I interpret that to mean that if you detect a significant correlation of XX bioindicator with pCO2, you cannot distinguish that effect from a correlation with O2. If pCO2 and O2 covary, you cannot separate their effects and test for them independently, as shown in Figure 5. Furthermore, in your forum response, you say "Because the VIF value for carbonate chemistry parameters and oxygen were above the threshold, we have not attempted to separate the effects of carbonate chemistry parameters (Ωar, pH and/or pCO2) from oxygen." However, O2 and pH and pCO2 are all shown with independent p-values in Figure 5. So, it is not clear to me how you used the VIF results. Perhaps additional text to the methods is needed to describe what you did with the results of the VIFs and how that influenced the statistical analysis that resultsed in Figure 5. Perhaps you could include the list of VIF values to support your decisions.__

We appreciate the reviewer's concern regarding clarification of the methods and we offer an explanation here to better describe our approach.  The reviewer is absolutely correct about collinearity between some of the drivers and the inability to separate the effects, as for pCO2, ph, and O2.  Our previous statistical design, although insufficiently described, was developed specifically to emphasize these limitations and to account for these issues in both analysis and interpretation of results.  Our analysis design first explored general relationships among environmental and pteropod response measures using multivariate analysis (RDA) and simple pairwise correlations (Figs. 4 and 5).  The second portion of our analysis provided a more formal framework to identify combined effects of stressors using linear models of pairwise combinations of environmental variables to explain pteropod response (Figs. 6 and 7).  This second portion was informed by the preceding exploratory analyses and included restrictions on which variables were evaluated due to collinaerity, using VIF thresholds.  As such, the results from the second set of analyses were used directly to infer relationships becuase of a robust design that accounted for collinearity.  Figures 4 and 5 were intended to demonstrate how the parameters covaried and we did not use them to directly infer causation.  

To address these concerns, we have added some content to the methods to better describe the methods and partciularly to distinguish between the different objectives of the first and second set of analyses (beginning on line 213, first paragraph of statistical analyses section):

"Several of the environmental variables were correlated, which presented a challenge for inferring causal relationships with pteropod response measures.  To address this issue, the analysis was conducted in two stages where the first was exploratory and the second was a more formal approach using a subset of the environmental variables to directly infer causation.  The first set of analyses included all variables to demonstrate the complexity of the environmental dataset and directly informed the second set of analyses, whereby variables that were associated with the response measures were further screened to reduce collinearity in subsequent models.  Details for both sets of analyses follow."

Finally, we note that the VIF values for all pairwise comparisons of collinearity of the environmental variables can be viewed in the supplementary online material indicated at the end of the mansucript.  Therefore, we have not included additional tables for this information.

